version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-board
    restart: always
    environment:
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
